### PR TITLE
Create nodewizard-gentx.json

### PR DESCRIPTION
**Pull request by Nodejssx**

### CODE REVIEW

**Comment by nicolam1** [comment]
This PR is done in the wrong path

**Comment by Nodejssx** [comment]
Can I create a wallet and edit the pr again on August 1st?

Nicola O ***@***.***>, 29 Tem 2022 Cum, 14:30 tarihinde şunu
yazdı:

**Comment by Nodejssx** [comment]
fixed.. check please.

**Comment by Nodejssx** [comment]
nodejssx#0502

**Pull request merged**
